package by.tr.xml.parsers.bean;

public enum WebTagName {
	WEB_APP,DISPLAY_NAME,WELCOME_FILE_LIST,FILTER,INIT_PARAM,
	FILTER_MAPPING,LISTENER,SERVLET,SERVLET_MAPPING,ERROR_PAGE,
	
	WELCOME_FILE,FILTER_NAME,FILTER_CLASS,PARAM_NAME,PARAM_VALUE,
	URL_PATTERN,DISPATCHER,LISTENER_CLASS,SERVLET_NAME,SERVLET_CLASS,
	EXCEPTION_TYPE,ERROR_CODE,LOCATION
}
