-- MySQL Script generated by MySQL Workbench
-- 01/08/17 22:45:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`clients` (
  `c_id` INT NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(255) NOT NULL,
  `c_surname` VARCHAR(255) NOT NULL,
  `c_email` VARCHAR(45) NOT NULL,
  `c_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`category` (
  `ct_id` INT NOT NULL AUTO_INCREMENT,
  `ct_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ct_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`equipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`equipments` (
  `e_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `e_title` VARCHAR(255) NOT NULL,
  `e_price` DOUBLE NOT NULL,
  `e_amount` INT NOT NULL,
  PRIMARY KEY (`e_id`),
  INDEX `fk_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `shop`.`category` (`ct_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`rented_units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`rented_units` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `eq_id` INT NOT NULL,
  PRIMARY KEY (`r_id`),
  INDEX `client_id_idx` (`client_id` ASC),
  INDEX `eq_id_idx` (`eq_id` ASC),
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `shop`.`clients` (`c_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `eq_id`
    FOREIGN KEY (`eq_id`)
    REFERENCES `shop`.`equipments` (`e_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `shop`.`clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`) VALUES (DEFAULT, 'Petr', 'Petrov', 'dodo', '123');
INSERT INTO `shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`) VALUES (DEFAULT, 'Vlad', 'Vladov', 'aaa', '321');
INSERT INTO `shop`.`clients` (`c_id`, `c_name`, `c_surname`, `c_email`, `c_password`) VALUES (DEFAULT, 'Ivan', 'Sidorov', 'qqq', '111');

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`category` (`ct_id`, `ct_name`) VALUES (DEFAULT, 'Cat1');
INSERT INTO `shop`.`category` (`ct_id`, `ct_name`) VALUES (DEFAULT, 'Cat2');
INSERT INTO `shop`.`category` (`ct_id`, `ct_name`) VALUES (DEFAULT, 'Cat3');

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`equipments`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`equipments` (`e_id`, `category_id`, `e_title`, `e_price`, `e_amount`) VALUES (DEFAULT, 1, 'koko', 12.2, 8);
INSERT INTO `shop`.`equipments` (`e_id`, `category_id`, `e_title`, `e_price`, `e_amount`) VALUES (DEFAULT, 3, 'lolo', 21.8, 18);
INSERT INTO `shop`.`equipments` (`e_id`, `category_id`, `e_title`, `e_price`, `e_amount`) VALUES (DEFAULT, 2, 'pepe', 14.5, 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `shop`.`rented_units`
-- -----------------------------------------------------
START TRANSACTION;
USE `shop`;
INSERT INTO `shop`.`rented_units` (`r_id`, `client_id`, `eq_id`) VALUES (DEFAULT, 1, 3);
INSERT INTO `shop`.`rented_units` (`r_id`, `client_id`, `eq_id`) VALUES (DEFAULT, 1, 2);
INSERT INTO `shop`.`rented_units` (`r_id`, `client_id`, `eq_id`) VALUES (DEFAULT, 1, 1);
INSERT INTO `shop`.`rented_units` (`r_id`, `client_id`, `eq_id`) VALUES (DEFAULT, 2, 1);
INSERT INTO `shop`.`rented_units` (`r_id`, `client_id`, `eq_id`) VALUES (DEFAULT, 3, 2);
INSERT INTO `shop`.`rented_units` (`r_id`, `client_id`, `eq_id`) VALUES (DEFAULT, 2, 3);

COMMIT;

